select FACT.Inspection_ID, 
	DIM_INSPECTION_DATE.*, 
	DIM_INSPECTION_TYPE.*, 
	DIM_CITY.*,
	DIM_FACILITY_TYPE.*,
	DIM_RESULTS.*,
	DIM_RISK.*,
	DIM_ADDRESS.Address,
	DIM_ADDRESS.ADDRESS_ID,
	DIM_DBA_NAME.DBA_Name,
	DIM_DBA_NAME.DBA_Name_ID,
	DIM_DBA_NAME.License
	into pivot_t
from DIM_ADDRESS, 
	DIM_CITY, 
	DIM_DBA_NAME, 
	DIM_FACILITY_TYPE, 
	DIM_INSPECTION_DATE, 
	DIM_INSPECTION_TYPE, 
	DIM_RESULTS,
	DIM_RISK, 
	FACT
where FACT.DBA_Name_ID=DIM_DBA_NAME.DBA_Name_ID and 
	FACT.Inspection_Date=DIM_INSPECTION_DATE.Inspection_Date and
	FACT.Inspection_Type=DIM_INSPECTION_TYPE.Inspection_Type and
	FACT.Results=DIM_RESULTS.Results and
	FACT.Risk=DIM_RISK.Risk and
	DIM_DBA_NAME.ADDRESS_ID=DIM_ADDRESS.ADDRESS_ID and
	DIM_DBA_NAME.Facility_Type=DIM_FACILITY_TYPE.Facility_Type and
	DIM_ADDRESS.City=DIM_CITY.City